# Azure Data Factory Export and Restore Pipeline

trigger: none

variables:
  - group: azure-data-factory-variables

pool:
  name: Default

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'demo-rg'
    ScriptType: 'InlineScript'
    Inline: |
      # Import the required Azure modules
      Import-Module Az.DataFactory
      Import-Module Az.Resources

      # Function to export the Data Factory ARM template
      function Export-DataFactoryArmTemplate {
          param(
              [string]$ResourceGroupName,
              [string]$DataFactoryName,
              [string]$ExportPath
          )

          $context = Get-AzContext
          $dataFactoryClient = Get-AzDataFactoryClient -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName
          $resourceManager = [Microsoft.Azure.Management.DataFactory.ResourceManager]::new($dataFactoryClient.DataFactoryName, $context.Subscription.Id)
          $armTemplate = $resourceManager.GetResourceManagerTemplate()

          $armTemplate | ConvertTo-Json -Depth 32 | Out-File $ExportPath
      }

      # Export ARM template from source Data Factory
      $sourceDataFactoryName = "$(source-data-factory-name)"
      $sourceResourceGroupName = "$(source-data-factory-rg)"
      $exportPath = Join-Path "$(Build.ArtifactStagingDirectory)" "$sourceDataFactoryName.json"

      Export-DataFactoryArmTemplate -ResourceGroupName $sourceResourceGroupName -DataFactoryName $sourceDataFactoryName -ExportPath $exportPath

      # Publish ARM template artifact
      Publish-Pipeline-Artifact -Path $exportPath -Artifact "data-factory-arm-template"
    azurePowerShellVersion: 'LatestVersion'
    
- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'data-factory-arm-template'
    targetPath: '$(Pipeline.Workspace)'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'demo-rg'
    ScriptType: 'InlineScript'
    Inline: |
      # Import the required Azure modules
      Import-Module Az.DataFactory
      Import-Module Az.Resources

      # Function to restore the Data Factory ARM template
      function Restore-DataFactoryArmTemplate {
          param(
              [string]$ResourceGroupName,
              [string]$DataFactoryName,
              [string]$ArmTemplatePath
          )

          $armTemplate = Get-Content -Path $ArmTemplatePath | ConvertFrom-Json
          New-AzResourceGroupDeployment -ResourceGroupName $ResourceGroupName -TemplateObject $armTemplate -DataFactoryName $DataFactoryName -Force
      }

      # Restore ARM template to target Data Factory
      $targetDataFactoryName = "$(target-data-factory-name)"
      $targetResourceGroupName = "$(target-data-factory-rg)"
      $armTemplatePath = Join-Path "$(Pipeline.Workspace)" "data-factory-arm-template/$(source-data-factory-name).json"

      Restore-DataFactoryArmTemplate -ResourceGroupName $targetResourceGroupName -DataFactoryName $targetDataFactoryName -ArmTemplatePath $armTemplatePath
    azurePowerShellVersion: 'LatestVersion'
